//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado_Services.JugadorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaDeNacimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rol {
            get {
                return this.RolField;
            }
            set {
                if ((this.RolField.Equals(value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaDeNacimiento {
            get {
                return this.fechaDeNacimientoField;
            }
            set {
                if ((this.fechaDeNacimientoField.Equals(value) != true)) {
                    this.fechaDeNacimientoField = value;
                    this.RaisePropertyChanged("fechaDeNacimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JugadorService.IJugadorService")]
    public interface IJugadorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/RegistrarJugador", ReplyAction="http://tempuri.org/IJugadorService/RegistrarJugadorResponse")]
        bool RegistrarJugador(Ahorcado_Services.JugadorService.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/RegistrarJugador", ReplyAction="http://tempuri.org/IJugadorService/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(Ahorcado_Services.JugadorService.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/IniciarSesion", ReplyAction="http://tempuri.org/IJugadorService/IniciarSesionResponse")]
        Ahorcado_Services.JugadorService.Jugador IniciarSesion(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/IniciarSesion", ReplyAction="http://tempuri.org/IJugadorService/IniciarSesionResponse")]
        System.Threading.Tasks.Task<Ahorcado_Services.JugadorService.Jugador> IniciarSesionAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ActualizarInformacionJugador", ReplyAction="http://tempuri.org/IJugadorService/ActualizarInformacionJugadorResponse")]
        bool ActualizarInformacionJugador(Ahorcado_Services.JugadorService.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ActualizarInformacionJugador", ReplyAction="http://tempuri.org/IJugadorService/ActualizarInformacionJugadorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInformacionJugadorAsync(Ahorcado_Services.JugadorService.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ExisteJugador", ReplyAction="http://tempuri.org/IJugadorService/ExisteJugadorResponse")]
        bool ExisteJugador(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ExisteJugador", ReplyAction="http://tempuri.org/IJugadorService/ExisteJugadorResponse")]
        System.Threading.Tasks.Task<bool> ExisteJugadorAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJugadorServiceChannel : Ahorcado_Services.JugadorService.IJugadorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JugadorServiceClient : System.ServiceModel.ClientBase<Ahorcado_Services.JugadorService.IJugadorService>, Ahorcado_Services.JugadorService.IJugadorService {
        
        public JugadorServiceClient() {
        }
        
        public JugadorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JugadorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarJugador(Ahorcado_Services.JugadorService.Jugador jugador) {
            return base.Channel.RegistrarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(Ahorcado_Services.JugadorService.Jugador jugador) {
            return base.Channel.RegistrarJugadorAsync(jugador);
        }
        
        public Ahorcado_Services.JugadorService.Jugador IniciarSesion(string correo, string contrasena) {
            return base.Channel.IniciarSesion(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<Ahorcado_Services.JugadorService.Jugador> IniciarSesionAsync(string correo, string contrasena) {
            return base.Channel.IniciarSesionAsync(correo, contrasena);
        }
        
        public bool ActualizarInformacionJugador(Ahorcado_Services.JugadorService.Jugador jugador) {
            return base.Channel.ActualizarInformacionJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInformacionJugadorAsync(Ahorcado_Services.JugadorService.Jugador jugador) {
            return base.Channel.ActualizarInformacionJugadorAsync(jugador);
        }
        
        public bool ExisteJugador(string correo) {
            return base.Channel.ExisteJugador(correo);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteJugadorAsync(string correo) {
            return base.Channel.ExisteJugadorAsync(correo);
        }
    }
}
