//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalabraService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Palabra : object
    {
        
        private PalabraService.Categoria CategoriaField;
        
        private string DescripcionField;
        
        private string DescripcionInglesField;
        
        private int IdField;
        
        private int IdCategoriaField;
        
        private int IdDificultadField;
        
        private string IdiomaPartidaField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        private PalabraService.Dificultad dificultadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PalabraService.Categoria Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionIngles
        {
            get
            {
                return this.DescripcionInglesField;
            }
            set
            {
                this.DescripcionInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDificultad
        {
            get
            {
                return this.IdDificultadField;
            }
            set
            {
                this.IdDificultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdiomaPartida
        {
            get
            {
                return this.IdiomaPartidaField;
            }
            set
            {
                this.IdiomaPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PalabraService.Dificultad dificultad
        {
            get
            {
                return this.dificultadField;
            }
            set
            {
                this.dificultadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Categoria : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dificultad", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Dificultad : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        private PalabraService.Palabra[] PalabrasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PalabraService.Palabra[] Palabras
        {
            get
            {
                return this.PalabrasField;
            }
            set
            {
                this.PalabrasField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PalabraService.IPalabraService")]
    public interface IPalabraService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerPalabra", ReplyAction="http://tempuri.org/IPalabraService/ObtenerPalabraResponse")]
        System.Threading.Tasks.Task<PalabraService.Palabra> ObtenerPalabraAsync(int IdPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerPalabrasPorFiltro", ReplyAction="http://tempuri.org/IPalabraService/ObtenerPalabrasPorFiltroResponse")]
        System.Threading.Tasks.Task<PalabraService.Palabra[]> ObtenerPalabrasPorFiltroAsync(int idCatergoria, int idDificultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/RegistrarPalabra", ReplyAction="http://tempuri.org/IPalabraService/RegistrarPalabraResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPalabraAsync(PalabraService.Palabra palabra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPalabraServiceChannel : PalabraService.IPalabraService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PalabraServiceClient : System.ServiceModel.ClientBase<PalabraService.IPalabraService>, PalabraService.IPalabraService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PalabraServiceClient() : 
                base(PalabraServiceClient.GetDefaultBinding(), PalabraServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPalabraService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PalabraServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PalabraServiceClient.GetBindingForEndpoint(endpointConfiguration), PalabraServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PalabraServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PalabraServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PalabraServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PalabraServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PalabraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PalabraService.Palabra> ObtenerPalabraAsync(int IdPalabra)
        {
            return base.Channel.ObtenerPalabraAsync(IdPalabra);
        }
        
        public System.Threading.Tasks.Task<PalabraService.Palabra[]> ObtenerPalabrasPorFiltroAsync(int idCatergoria, int idDificultad)
        {
            return base.Channel.ObtenerPalabrasPorFiltroAsync(idCatergoria, idDificultad);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPalabraAsync(PalabraService.Palabra palabra)
        {
            return base.Channel.RegistrarPalabraAsync(palabra);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPalabraService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPalabraService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55459/Aplicacion/Implementacion/PalabraService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PalabraServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPalabraService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PalabraServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPalabraService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPalabraService,
        }
    }
}
