//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JugadorServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Jugador : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string ContrasenaField;
        
        private string CorreoField;
        
        private int IdField;
        
        private string NombreField;
        
        private int PuntajeField;
        
        private string TelefonoField;
        
        private string UsernameField;
        
        private System.DateTime fechaDeNacimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena
        {
            get
            {
                return this.ContrasenaField;
            }
            set
            {
                this.ContrasenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje
        {
            get
            {
                return this.PuntajeField;
            }
            set
            {
                this.PuntajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaDeNacimiento
        {
            get
            {
                return this.fechaDeNacimientoField;
            }
            set
            {
                this.fechaDeNacimientoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JugadorServiceReference.IJugadorService")]
    public interface IJugadorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/RegistrarJugador", ReplyAction="http://tempuri.org/IJugadorService/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(JugadorServiceReference.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/IniciarSesion", ReplyAction="http://tempuri.org/IJugadorService/IniciarSesionResponse")]
        System.Threading.Tasks.Task<JugadorServiceReference.Jugador> IniciarSesionAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ActualizarInformacionJugador", ReplyAction="http://tempuri.org/IJugadorService/ActualizarInformacionJugadorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInformacionJugadorAsync(JugadorServiceReference.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ExisteJugador", ReplyAction="http://tempuri.org/IJugadorService/ExisteJugadorResponse")]
        System.Threading.Tasks.Task<bool> ExisteJugadorAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugadorService/ObtenerJugadorPorId", ReplyAction="http://tempuri.org/IJugadorService/ObtenerJugadorPorIdResponse")]
        System.Threading.Tasks.Task<JugadorServiceReference.Jugador> ObtenerJugadorPorIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IJugadorServiceChannel : JugadorServiceReference.IJugadorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class JugadorServiceClient : System.ServiceModel.ClientBase<JugadorServiceReference.IJugadorService>, JugadorServiceReference.IJugadorService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JugadorServiceClient() : 
                base(JugadorServiceClient.GetDefaultBinding(), JugadorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IJugadorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JugadorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JugadorServiceClient.GetBindingForEndpoint(endpointConfiguration), JugadorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JugadorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JugadorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JugadorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JugadorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JugadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(JugadorServiceReference.Jugador jugador)
        {
            return base.Channel.RegistrarJugadorAsync(jugador);
        }
        
        public System.Threading.Tasks.Task<JugadorServiceReference.Jugador> IniciarSesionAsync(string correo, string contrasena)
        {
            return base.Channel.IniciarSesionAsync(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInformacionJugadorAsync(JugadorServiceReference.Jugador jugador)
        {
            return base.Channel.ActualizarInformacionJugadorAsync(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteJugadorAsync(string correo)
        {
            return base.Channel.ExisteJugadorAsync(correo);
        }
        
        public System.Threading.Tasks.Task<JugadorServiceReference.Jugador> ObtenerJugadorPorIdAsync(int id)
        {
            return base.Channel.ObtenerJugadorPorIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJugadorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJugadorService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55459/Aplicacion/Implementacion/JugadorService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JugadorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IJugadorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JugadorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IJugadorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IJugadorService,
        }
    }
}
