//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartidaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Partida : object
    {
        
        private PartidaService.EstadoPartida EstadoPartidaField;
        
        private System.DateTime FechaCreacionPartidaField;
        
        private int IdField;
        
        private int IdEstadoPartidaField;
        
        private int IdJugadorAnfitrionField;
        
        private int IdJugadorInvitadoField;
        
        private int IdPalabraSelecionadaField;
        
        private int IntentosRestantesField;
        
        private PartidaService.Palabra PalabraField;
        
        private string PalabraParcialField;
        
        private bool PartidaGanadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.EstadoPartida EstadoPartida
        {
            get
            {
                return this.EstadoPartidaField;
            }
            set
            {
                this.EstadoPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacionPartida
        {
            get
            {
                return this.FechaCreacionPartidaField;
            }
            set
            {
                this.FechaCreacionPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoPartida
        {
            get
            {
                return this.IdEstadoPartidaField;
            }
            set
            {
                this.IdEstadoPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugadorAnfitrion
        {
            get
            {
                return this.IdJugadorAnfitrionField;
            }
            set
            {
                this.IdJugadorAnfitrionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugadorInvitado
        {
            get
            {
                return this.IdJugadorInvitadoField;
            }
            set
            {
                this.IdJugadorInvitadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPalabraSelecionada
        {
            get
            {
                return this.IdPalabraSelecionadaField;
            }
            set
            {
                this.IdPalabraSelecionadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntentosRestantes
        {
            get
            {
                return this.IntentosRestantesField;
            }
            set
            {
                this.IntentosRestantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.Palabra Palabra
        {
            get
            {
                return this.PalabraField;
            }
            set
            {
                this.PalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalabraParcial
        {
            get
            {
                return this.PalabraParcialField;
            }
            set
            {
                this.PalabraParcialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PartidaGanada
        {
            get
            {
                return this.PartidaGanadaField;
            }
            set
            {
                this.PartidaGanadaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPartida", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class EstadoPartida : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private PartidaService.Partida[] PartidasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.Partida[] Partidas
        {
            get
            {
                return this.PartidasField;
            }
            set
            {
                this.PartidasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Palabra : object
    {
        
        private PartidaService.Categoria CategoriaField;
        
        private string DescripcionField;
        
        private string DescripcionInglesField;
        
        private int IdField;
        
        private int IdCategoriaField;
        
        private int IdDificultadField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        private PartidaService.Dificultad dificultadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.Categoria Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionIngles
        {
            get
            {
                return this.DescripcionInglesField;
            }
            set
            {
                this.DescripcionInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDificultad
        {
            get
            {
                return this.IdDificultadField;
            }
            set
            {
                this.IdDificultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.Dificultad dificultad
        {
            get
            {
                return this.dificultadField;
            }
            set
            {
                this.dificultadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Categoria : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dificultad", Namespace="http://schemas.datacontract.org/2004/07/Ahorcado_Services.Modelo.EntityFramework")]
    public partial class Dificultad : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string NombreInglesField;
        
        private PartidaService.Palabra[] PalabrasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngles
        {
            get
            {
                return this.NombreInglesField;
            }
            set
            {
                this.NombreInglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PartidaService.Palabra[] Palabras
        {
            get
            {
                return this.PalabrasField;
            }
            set
            {
                this.PalabrasField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartidaService.IPartidaService")]
    public interface IPartidaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ObtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IPartidaService/ObtenerPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<PartidaService.Partida[]> ObtenerPartidasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ObtenerTodasLasPartidas", ReplyAction="http://tempuri.org/IPartidaService/ObtenerTodasLasPartidasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> ObtenerTodasLasPartidasAsync(int IdJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPartidaServiceChannel : PartidaService.IPartidaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PartidaServiceClient : System.ServiceModel.ClientBase<PartidaService.IPartidaService>, PartidaService.IPartidaService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PartidaServiceClient() : 
                base(PartidaServiceClient.GetDefaultBinding(), PartidaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPartidaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PartidaServiceClient.GetBindingForEndpoint(endpointConfiguration), PartidaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PartidaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PartidaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PartidaService.Partida[]> ObtenerPartidasDisponiblesAsync()
        {
            return base.Channel.ObtenerPartidasDisponiblesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> ObtenerTodasLasPartidasAsync(int IdJugador)
        {
            return base.Channel.ObtenerTodasLasPartidasAsync(IdJugador);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPartidaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPartidaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55459/Aplicacion/Implementacion/PartidaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PartidaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPartidaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PartidaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPartidaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPartidaService,
        }
    }
}
